{
  description = "massivebird's static site generated by zola";

  inputs = {
    nixpkgs.url      = "github:NixOS/nixpkgs/nixos-23.11";
  };

  outputs = { self, nixpkgs, flake-utils, ... }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs {
          inherit system;
        };
      in
      with pkgs;
      {
        devShell = mkShell {
          buildInputs = [
            neovim
            zola
          ];
        };
      }
    );
}
